### ISSUE TITLE
Failed Image Creation

### ISSUE THREAD

**Issue by ishuverma** [gicmo/rfe-demo#10]
Image creation failed due to insufficient space error (see log below). 
Tried to increase the storage size in install.py but still got the error.

<snip>
Output:
[/usr/lib/tmpfiles.d/journal-nocow.conf:26] Failed to resolve specifier: uninitialized /etc detected, skipping
All rules containing unresolvable specifiers will be skipped.
Failed to create file /sys/fs/selinux/checkreqprot: Read-only file system
Committing...done
error: While writing rootfs to mtree: Writing content object: min-free-space-percent '3%' would be exceeded, at least 34.3 MB requested
Initializing root filesystem
Copying data
Traceback (most recent call last):
  File "/run/osbuild/lib/assemblers/org.osbuild.ostree.commit", line 172, in <module>
    r = main(args["tree"], args["output_dir"], args["options"], args["meta"])
  File "/run/osbuild/lib/assemblers/org.osbuild.ostree.commit", line 152, in main
    check=True)
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['rpm-ostree', 'compose', 'commit', '--repo=/run/osbuild/output/repo', '--add-metadata-string=rpmostree.inputhash=d591f0a84ef1cf62984fab2cffd2a99da01a75a8dc289ba3d96357934e78fb7c', '--write-composejson-to=/run/osbuild/output/compose.json', '/tmp/tmph6q347e0.json', '/run/osbuild/output/tmpu920yn3b']' returned non-zero exit status 1.

**Comment by mrguitar** [comment]
Ishu, I still haven't been able to recreate this. We just updated everything for 8.4, and the defaults in install.py are working fine here. I'm going to close this issue, but please let me know if you run into problems tying again. Thanks!
