### ISSUE TITLE
kdump.service fails to start on ostree deployment

### ISSUE THREAD

**Issue by dnoliver** [gicmo/rfe-demo#2]
By following this instructions, and using the `edge.ks` file, I got an image that has `kdump.service` enabled by default.
The kdump service fails to start.

Is that expected to work?
or should it be disabled by default in the provided edge.ks file? 

```shell
[core@rhel-ostree ~]$ systemctl status kdump.service 
● kdump.service - Crash recovery kernel arming
   Loaded: loaded (/usr/lib/systemd/system/kdump.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-08-20 19:37:21 UTC; 1min 21s ago
  Process: 1031 ExecStart=/usr/bin/kdumpctl start (code=exited, status=1/FAILURE)
 Main PID: 1031 (code=exited, status=1/FAILURE)

Aug 20 19:37:20 rhel-ostree.mshome.net systemd[1]: Starting Crash recovery kernel arming...
Aug 20 19:37:21 rhel-ostree.mshome.net kdumpctl[1031]: No kdump initial ramdisk found.
Aug 20 19:37:21 rhel-ostree.mshome.net kdumpctl[1031]: Rebuilding /boot(hd0,gpt2)/ostree/rhel-5b70c6dfc52e572557f5e1bae041f42936b66334d7ea94336d4876cd389d4732/initramfs-4.18.0-221.el8.x86_64kdump.img
Aug 20 19:37:21 rhel-ostree.mshome.net kdumpctl[1031]: /boot(hd0,gpt2)/ostree/rhel-5b70c6dfc52e572557f5e1bae041f42936b66334d7ea94336d4876cd389d4732 does not have write permission. Can not rebuild /boot(hd0,>
Aug 20 19:37:21 rhel-ostree.mshome.net kdumpctl[1031]: Starting kdump: [FAILED]
Aug 20 19:37:21 rhel-ostree.mshome.net systemd[1]: kdump.service: Main process exited, code=exited, status=1/FAILURE
Aug 20 19:37:21 rhel-ostree.mshome.net systemd[1]: kdump.service: Failed with result 'exit-code'.
Aug 20 19:37:21 rhel-ostree.mshome.net systemd[1]: Failed to start Crash recovery kernel arming
```

**Comment by mrguitar** [comment]
In general, we'd only recommend kdump for testing. It can potentially cause more issues in remote deployments than it solves. Remember, kdump isn't installed via the kickstart per say, but you could certainly disable it there if you wanted to. My nodes do not have kdump installed or activated. I'm guessing we dropped it in a later revision of the "edge" image type in osbuild. tl;dr, I wouldn't worry about it unless you actively need kdump for testing.

**Comment by dnoliver** [comment]
I think I was reading the wrong kickstart file 

```shell
bash-4.4# cat anaconda-ks.cfg | grep kdump
%addon com_redhat_kdump --enable --reserve-mb='auto'
```

But the edge.ks file provided here does not have the plugin enabled.
Maybe it takes it from the RHEL 3.8 Beta host that I am using to compose the ostree?  Because that one have kdump enabled by default (I assume it will be removed once 3.8 is GA)

**Comment by mrguitar** [comment]
this wasn't an issue in later beta builds. Closing.
