### ISSUE TITLE
GUI installation of RHEL Edge not working 

### ISSUE THREAD

**Issue by dnoliver** [gicmo/rfe-demo#5]
Using this ks file, which is a modified version of the default one to enable GUI installation,

```shell
lang en_US.UTF-8
keyboard us
timezone UTC
zerombr
clearpart --all --initlabel
autopart --type=plain --fstype=xfs --nohome
reboot
network --bootproto=dhcp
user --name=core --groups=wheel --password=edge
services --enabled=ostree-remount
ostreesetup --nogpg --url=http://192.168.122.171/ostree/repo --osname=rhel --remote=edge --ref=rhel/8/x86_64/edge
```

I am getting the following error related to CDN

![image](https://user-images.githubusercontent.com/7730267/91351170-b3762400-e79c-11ea-8b85-c9ac22433735.png)

**Comment by mrguitar** [comment]
I believe this was fixed, but there's a new subscription-manager plugin in anaconda that triggers this error. Using "text" in the example bypasses the plug-in and you won't hit this.

**Comment by dnoliver** [comment]
Yes, using text works fine. 

I need the GUI to have the initial ks file generated, otherwise it is trial and error for me trying to correctly set up custom partitions :)

**Comment by mrguitar** [comment]
Ah! I see what you're doing. There are a bunch of kickstart generator tools out there that can help, but alternatively you can temporarily comment out the ostreesetup line, and add:

%packages
@core 

and you can scrape the generated ks config w/ your partitions.

**Comment by mrguitar** [comment]
Closing, from the last workaround. Alos, if you create an installer image in 8.4 clients will have a graphical environment for any network & storage configs.
